import { Inter } from "next/font/google";
import "./gallery.css";
// import "cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/css/lightbox.min.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "sample",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <script src="gallery.js" async></script>
      <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"  async></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox.min.js"  async></script>
      <body>{children}</body>
    </html>
  );
}
